version: '3'

services:
  bitcoind:
    build: .
    image: bitcoind:latest
    container_name: bitcoind
    env_file: .env
    hostname: bitcoind
    init: true
    restart: unless-stopped
    tty: true
    volumes:
      - ./config:/config:ro
      - ./data:/data:rw
      - ./shared:/root/share:rw
